spring:
  application:
    name: circleguard-gateway-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret: "my-super-secret-dev-key-32-chars-long-12345678"
  expiration: 3600000

qr:
  secret: "my-qr-secret-key-for-dev-1234567890"
  expiration: 300

server:
  port: 8087

services:
  promotion-url: ${CIRCLEGUARD_PROMOTION_SERVICE_URL:http://promotion-service:8088}

resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      promotionService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        recordExceptions:
          - org.springframework.web.client.RestClientException
          - java.io.IOException
  retry:
    retryAspectOrder: 2
    instances:
      promotionService:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.RestClientException
          - java.io.IOException
