apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE DATABASE circleguard_identity;
      CREATE DATABASE circleguard_form;
      CREATE DATABASE circleguard_promotion;
      CREATE DATABASE circleguard_dashboard;
      CREATE DATABASE circleguard_file;
    EOSQL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: circleguard-postgres
  template:
    metadata:
      labels:
        app: circleguard-postgres
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: circleguard-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: circleguard-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: circleguard_auth
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          lifecycle:
            preStop:
              exec:
                command: ["su", "-", "postgres", "-c", "pg_ctl stop -m fast -D /var/lib/postgresql/data/pgdata"]
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-scripts
          configMap:
            name: postgres-init
            defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-postgres
spec:
  selector:
    app: circleguard-postgres
  ports:
    - port: 5432
      targetPort: 5432
