FROM gradle:8-jdk21 AS builder
WORKDIR /app
COPY build.gradle.kts settings.gradle.kts gradlew ./
COPY gradle ./gradle
COPY services/circleguard-file-service ./services/circleguard-file-service
RUN gradle :services:circleguard-file-service:bootJar -x test --no-daemon

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/services/circleguard-file-service/build/libs/*.jar app.jar
RUN mkdir -p /app/uploads
EXPOSE 8085
ENTRYPOINT ["java", "-jar", "app.jar"]
