apiVersion: v1
kind: ServiceAccount
metadata:
  name: form-service-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: form-service-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: circleguard-service-role
subjects:
  - kind: ServiceAccount
    name: form-service-sa
