apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: circleguarddevacr.azurecr.io/circleguard-identity:latest
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: circleguard-config
            - secretRef:
                name: circleguard-secrets
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/circleguard_identity"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: circleguard-secrets
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: circleguard-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
              value: "5"
          startupProbe:
            tcpSocket:
              port: 8083
            failureThreshold: 60
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
